import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { ThemeProvider } from "./_providers/theme-provider";
import { SearchProvider } from "./_contexts/SearchContext";

export const metadata: Metadata = {
  title: "Cubo Tickets",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt_BR">
      <body className="bg-foreground text-primary">
        <SearchProvider>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <Navbar />
            <div className="pt-[58px]">{children}</div>
          </ThemeProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
